# Generated by Django 4.1.7 on 2023-03-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_datecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='iscompleted',
            field=models.BooleanField(default=False),
        ),
    ]
