# Generated by Django 4.1.7 on 2023-04-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
