# Generated by Django 4.1.7 on 2023-04-09 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
